from utils.gemini_client import ask_gemini

def answer_question(document_text, question, qa_history=None):

    prompt = f"""
    Document:
    {document_text[:50000]}

    Question:
    {question}

    Return in this format:

    ANSWER:
    <answer>

    JUSTIFICATION:
    <why this answer is correct>

    SNIPPET:
    <supporting text from the document>
    """

    response = ask_gemini(prompt)

    try:
        answer = response.split("JUSTIFICATION:")[0].replace("ANSWER:", "").strip()
        justification = response.split("JUSTIFICATION:")[1].split("SNIPPET:")[0].strip()
        snippet = response.split("SNIPPET:")[1].strip()
    except:
        answer = response
        justification = "Generated by Gemini"
        snippet = "Not available"

    return answer, justification, snippet
